export const demoVehicles = [
  {
    id: 1,
    vehicle_name: 'Sprinter Van 01',
    license_plate: 'FLT-2847',
    status: 'active',
    driver_name: 'Michael Chen',
    location: 'Downtown District',
    last_update: new Date(Date.now() - 15 * 60000).toISOString(),
    mileage: 45234,
    fuel_level: 78,
    next_maintenance: new Date(Date.now() + 7 * 24 * 60 * 60000).toISOString(),
    maintenance_due: false,
  },
  {
    id: 2,
    vehicle_name: 'Cargo Truck 03',
    license_plate: 'FLT-1923',
    status: 'active',
    driver_name: 'Sarah Rodriguez',
    location: 'Warehouse Zone B',
    last_update: new Date(Date.now() - 8 * 60000).toISOString(),
    mileage: 89451,
    fuel_level: 45,
    next_maintenance: new Date(Date.now() + 2 * 24 * 60 * 60000).toISOString(),
    maintenance_due: true,
  },
  {
    id: 3,
    vehicle_name: 'Delivery Van 12',
    license_plate: 'FLT-5612',
    status: 'idle',
    driver_name: null,
    location: 'Main Depot',
    last_update: new Date(Date.now() - 120 * 60000).toISOString(),
    mileage: 34567,
    fuel_level: 92,
    next_maintenance: new Date(Date.now() + 14 * 24 * 60 * 60000).toISOString(),
    maintenance_due: false,
  },
  {
    id: 4,
    vehicle_name: 'Box Truck 07',
    license_plate: 'FLT-8834',
    status: 'maintenance',
    driver_name: null,
    location: 'Service Center',
    last_update: new Date(Date.now() - 240 * 60000).toISOString(),
    mileage: 102341,
    fuel_level: 15,
    next_maintenance: new Date().toISOString(),
    maintenance_due: true,
  },
  {
    id: 5,
    vehicle_name: 'Sprinter Van 08',
    license_plate: 'FLT-4422',
    status: 'active',
    driver_name: 'James Wilson',
    location: 'Airport Route',
    last_update: new Date(Date.now() - 5 * 60000).toISOString(),
    mileage: 56788,
    fuel_level: 68,
    next_maintenance: new Date(Date.now() + 21 * 24 * 60 * 60000).toISOString(),
    maintenance_due: false,
  },
  {
    id: 6,
    vehicle_name: 'Pickup Truck 15',
    license_plate: 'FLT-7731',
    status: 'idle',
    driver_name: null,
    location: 'North Yard',
    last_update: new Date(Date.now() - 180 * 60000).toISOString(),
    mileage: 67234,
    fuel_level: 55,
    next_maintenance: new Date(Date.now() + 10 * 24 * 60 * 60000).toISOString(),
    maintenance_due: false,
  },
]

export const demoStats = {
  total_vehicles: 6,
  active_vehicles: 3,
  idle_vehicles: 2,
  maintenance_vehicles: 1,
  average_fuel_level: 59,
  maintenance_alerts: 2,
}
